### Definição do baseUrl
@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/abrigos
Content-Type: application/json

{
  "nome": "Abrigo Esperança",
  "email": "abrigo@esperanca.com",
  "telefone": "123456789",
  "endereco": "Rua da Paz, 123",
  "capacidade": "50",
  "id_usuario": 1
}

### Requisição GET para listar todos os abrigos
GET {{baseUrl}}/abrigos
Accept: application/json

### Requisição GET para buscar um abrigos pelo ID
GET {{baseUrl}}/abrigos/1
Accept: application/json

### Requisição POST para criar um novo abrigo
POST {{baseUrl}}/abrigos
Content-Type: application/json

{
"nome": "Abrigo Esperança",
"email": "abrigo@esperanca.com",
"telefone": "123456789",
"endereco": "Rua da Paz, 123",
"capacidade": "50",
"id_usuario": 1
}

### Requisição PUT para atualizar um abrigo
PUT {{baseUrl}}/abrigos/1
Content-Type: application/json
Accept: application/json

{
    "nome": "Abrigo  atualizado",
    "email": "abrigo@esperanca.com",
    "telefone": "123456789",
    "endereco": "Rua da Paz, 123",
    "capacidade": 75,
    "id_usuario": 2
  }

### Requisição DELETE para excluir um abrigo
DELETE {{baseUrl}}/abrigos/1
Accept: application/json